#!/bin/bash
# get all logs in sorted order
# first parameter is the directory name
# second parameter is the flag file name

if [ ! -f $1/$2 ]; then
  touch 1101000072 $1/$2
fi
/usr/bin/clfmerge `find $1 -name "access.*" \! -name "*.gz" -newer $1/$2`
